SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `church`;

CREATE TABLE `church` (
  `name` varchar(500) DEFAULT NULL,
  `address` varchar(200) DEFAULT NULL,
  `city` varchar(500) DEFAULT NULL,
  `state` varchar(200) DEFAULT NULL,
  `zip` varchar(200) DEFAULT NULL,
  `pastor` varchar(200) DEFAULT NULL,
  `description` varchar(1000) DEFAULT NULL,
  `email` varchar(200) DEFAULT NULL,
  `phone` varchar(200) DEFAULT NULL,
  `image` varchar(200) DEFAULT NULL,
  `id` varchar(200) UNIQUE,

PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO church(name, address, city,state,zip,pastor,description,email,phone,image,id)
VALUES(
	'Primeira Igreja Batista Regular de Rio Branco',
    'Rua Marechal Deodoro 284, Centro, Caixa Postal 197',
    'Rio Branco',
    'Acre',
    '69900-210',
    'Emídio Viana',
    '',
    'emidio@contilnet.com.br',
    '3228-1917 , 3228-1925',
    '',
    '000002',
    ''
) ,
(
	'IGREJA BATISTA INDEPENDENTE MACEDÔNIA',
    'Rua J, 837 - Bairro: Ilson Ribeiro',
    'Rio Branco',
    'Acre',
    '69914-550',
    'Stephen Robert Doolitle',
    '',
    'emidio@contilnet.com.br',
    '(68) 9219-7720',
    '',
    '000002',
    ''
),
(
	'Igreja Batista Independente Metropolitana',
    'Rua Desembargador Carlos Gusmão, 208 (Próx.Terminal Ônibus Salvador Lyra)',
    'Maceió',
    'Alagoas',
    '',
    'Robert Tully',
    '',
    'tully@fbmi.org',
    '(82) 8815-4408',
    '',
    '000003',
    'http://www.batistametropolitana.com'
),
(
	'Igreja Batista Bíblica',
    'Travessa Frei Pascásio 81',
    'Junqueiro',
    'Alagoas',
    '',
    'Rosalvo Jesus Marinho Filho',
    '',
    '',
    '(82) 9920-7807',
    '',
    '000004',
    ''
) ,
(
	'Igreja Batista Regular Vale de Bênção',
    '',
    'Codajás',
    'Amazonas',
    '',
    'Miguel Ângelo Luis Maciel',
    '',
    'michael_angelo7 at yahoo.com',
    '',
    '',
    '000005',
    ''
),
(
	'Igreja Batista Independente',
    'Caixa Postal 81, Campos Sales',
    'Manaus',
    'Amazonas',
    '69011-970',
    'John Hawkins',
    'A igreja tem o Instituto Batista Bíblico do Amazonas.',
    'jhawkins@argo.com.br',
    '',
    '',
    '000006',
    ''
) , 
(
	'Igreja Batista Regular Moriá',
    'Beco São Francisco, Número. 98, Bairro Adrianópolis',
    'Manaus',
    'Amazonas',
    '',
    'Antônio Marques',
    'Só usa a ACF. Não se associou à AIBRAM.',
    '',
    '',
    '',
    '000007',
    ''
) , 
(
	'Congregação Batista Regular Águas Claras',
    'Rua 03, Número 14, Águas Claras – Cidade Nova I.',
    'Manaus',
    'Amazonas',
    '',
    '',
    '(subordinada à Igreja Batista Regular da Graça). Já foi supervisionada pelo Seminarista Miguel Ângelo L. Maciel',
    'michael_angelo7 at yahoo.com',
    '',
    '',
    '000008',
    ''
) ,
(
	'Igreja Batista Regular Siloé',
    'Bairro do São José I',
    'Manaus',
    'Amazonas',
    '',
    'Joanilson Azevedo',
    '',
    '',
    '',
    '',
    '000009',
    ''
) , 
(
	'Igreja Batista Regular da Colônia Antônio Aleixo',
    '',
    'Manaus',
    'Amazonas',
    '',
    '',
    'Estava sob o Seminarista Miguel Ângelo L. Maciel',
    'michael_angelo7 at yahoo.com',
    '',
    '',
    '000010',
    ''
) ,
(
	'CETEBRAM – Centro de Estudos Batista Regular da Amazônia',
    '',
    'Manaus',
    'Amazonas',
    '',
    '',
    '(não confundir com o SEBRAM (Seminário Batista Regular da Amazônia), que se corrompeu com tolerância às práticas mundanas de algumas igrejas (envolvimento político, músicas mundanas, etc))',
    '',
    '',
    '',
    '000011',
    ''
) , 
(
	'Templo Batista Bíblico Salém',
    'Rua Jardim Brasília, 22, Camaçari de Dentro',
    'Camaçari',
    'Bahia',
    '42806-200',
    'Milton França Fernandes',
    '',
    '',
    '(071) 3627-3910',
    '',
    '000012',
    ''
) , 
(
	'Igreja Batista Regular',
    '',
    'Feira de Santana',
    'Bahia',
    '',
    'Francisco Xavier',
    '',
    '',
    '',
    '',
    '000013',
    ''
) , 
(
	'Igreja Batista Bíblica Salém',
    'Rua Boa Esperança, 101, São Gonçalo do Retiro',
    'Salvador',
    'Bahia',
    '41185-010',
    'Humberto Vieira de Souza',
    '',
    'pastorhumberto@yahoo.com.br',
    '(071) 3384-6383 , 071.3385-4116',
    '',
    '000014',
    ''
) , 
(
	'Igreja Batista Bíblica Monte Sião',
    'Rua Feira de Santana, 100, bairro Cristo Rei',
    'Simões Filho',
    'Bahia',
    '43 700-000',
    'Edson Sarmento',
    '',
    '',
    '',
    '',
    '000015',
    ''
) , 
(
	'Primeira Igreja Batista do Jardim das Oliveiras',
    'Avenida Dr. João Maciel Filho , 207',
    'Fortaleza',
    'Ceará',
    '',
    'David A. Zuhars Jr.',
    '(O site desta igreja tem excelentes artigos, e Hélio tem alegria na concordância com todas as doutrinas e práticas desta igreja (inclusive combate à igreja universal), exceto que Hélio crê que ininterruptamente houve + há + haverá igrejas fiéis de doutrina batista rigorosamente bíblica, mas não chega à posição "sucessionista", isto é, não acredita que uma igreja batista local e um batismo por tal igreja só são válidos se ela foi formalmente organizada por outra igreja local válida, e assim por diante, retroagindo até onde os registros nos permitam. Hélio acredita que o que dá validade a uma igreja batista é sua biblicidade de doutrina e de prática, não seu "pedigree", não sua "árvore genealógica". Quanto ao Noivaísmo desta igreja, não é extremado, pois somente defende que a Noiva de Cristo é constituída somente por crentes batistas fiéis, deixando margem para que os outros demais crentes sejam salvos, embora não fazendo parte da Noiva. Por tudo isto, Hélio pode recomendar esta igreja.)',
    'pastor@pibjo.org.br.',
    '',
    '',
    '000016',
    'http://www.pibjo.org.br'
) , 
(
	'Igreja Batista do Planalto das Goiabeiras',
    'Rua Senador Robert Kennedy, 16, Barra do Ceará',
    'Fortaleza',
    'Ceará',
    '',
    '',
    'Organizada pela PIB Jardim das Oliveiras.',
    '',
    '',
    '',
    '000017',
    ''
) , 
(
	'Igreja Batista da Graça de Deus',
    'Rua Manuel Figueiredo, 15, Barroso',
    'Fortaleza',
    'Ceará',
    '',
    '',
    'Organizada pela PIB Jardim das Oliveiras',
    '',
    '',
    '',
    '000018',
    ''
) , 
(
	'Igreja Fundamentalista',
    'Rua Belém, 32, bairro Henrique Jorge',
    'Fortaleza',
    'Ceará',
    '',
    'Victor Emanuel Carneiro Vieira da Mata',
    'Maiores informações com Victor Emanuel Carneiro Vieira da Mata Mata',
    'prof_fort@yahoo.com.br',
    '',
    '',
    '000019',
    ''
) , 
(
	'Igreja Batista Fundamentalista Voz Bíblica',
    'Rua 2, n.22, Conj. Campo dos Ingleses (proximidades do Maraponga Mart Modas)',
    'Fortaleza',
    'Ceará',
    '',
    'José Laérton',
    '',
    '',
    '(85) 3296-9151 , (85) 9707-4201',
    '',
    '000020',
    ''
) , 
(
	'Congregação Batista Independente',
    'QRI 24,Casa 2, Residencial Santos Dumont, Bairro Santa Maria',
    'Brasília',
    'Distrito Federal',
    '72593-224',
    'José Pedro Monteiro de Almeida',
    '',
    ' chickbrasil@hotmail.com',
    '',
    '',
    '000021',
    ''
) , 
(
	'Templo Batista Maranata',
    'Rua 03, Qd. 28, Lt. 06-09, Bairro Independência',
    'Aparecida de Goiânia',
    'Goiás',
    '74967-020',
    'Éverton',
    '',
    'evertontbm@yahoo.com.br',
    '(62) 3248-7756',
    '',
    '000022',
    'www.tbm.org.br'
) , 
(
	'Templo Batista Maranata',
    'Av. C-15, Qd. 133, Lotes 13 e 14, Setor Sudoeste',
    'Goiânia',
    'Goiás',
    '',
    'Rômulo W. Ribeiro',
    '',
    '',
    '(62) 3247-4148',
    '',
    '000023',
    'www.tbm.org.br'
) , 
(
	'Templo Batista Ebenézer',
    'Av. Cristovão Colombo, Qd. 205, Lt. 25, Jd. Novo Mundo',
    'Goiânia',
    'Goiás',
    '74705-130',
    'Marcelo',
    '',
    'prmarcelo30@hotmail.com',
    '(62) 3206-3732 ',
    '',
    '000024',
    ''
) , 
(
	'Igreja Batista Bereana',
    'Rua Juscelino Kubistchek 80, Sala 03, Castelândia II',
    'Primavera do Leste',
    'Mato Grosso',
    '',
    'Miguel Maciel',
    '',
    'pr.miguel.maciel@gmail.com',
    '',
    '',
    '000025',
    ''
) , 
(
	'Igreja Batista Fiel',
    'Rua Rio Brilhante 38, Centro',
    'Bataguassu',
    'Mato Grosse do Sul',
    '79780-000',
    'Miguel Ângelo Maciel',
    '',
    '',
    '(67) 3541-1464',
    '',
    '000026',
    ''
) , 
(
	'Igreja Batista Fundamentalista em Três Lagoas',
    'Rua Plínio Alarcon 1234, Bairro Jardim das Oliveiras',
    'Três Lagoas',
    'Mato Grosso do Sul',
    '79630-213',
    'Marcelo de Oliveira Lima',
    '',
    'pr.marcelo3l@gmail.com',
    '(67) 3521-9124 , (67) 99138-0084 , (67)98166-6524',
    '',
    '000027',
    ''
) , 
(
	'Igreja Batista Independente',
    'Rua Cláudio Reis, 102, bairro Boticão',
    'Aguanil',
    'Minas Gerais',
    '',
    'Anderson Dantas',
    '',
    'andersondantas@yahoo.com.br',
    '',
    '',
    '000028',
    ''
) , 
(
	'Igreja Batista Bíblica Fundamentalista',
    'Rua Maria Amélia Melo, 417, Santa Helena ',
    'Belo Horizonte',
    'Minas Gerais',
    '30642-160',
    'Luiz Carlos Tibúrcio',
    '',
    'tiburcioluiz@ig.com.br',
    '(31) 3381-8905',
    '',
    '000029',
    ''
) , 
(
	'Congregação Batista Bíblica',
    'R: Dário Nogueira, 259 - São Judas Tadeu',
    'Borda da Mata',
    'Minas Gerais',
    '37564-000',
    'Natanael Rodrigues Nogueira',
    '',
    '',
    '',
    '',
    '000030',
    ''
) , 
(
	'Igreja Batista Bíblica Esperança',
    'Rua Sinésio Lopes Silveira, 180, bairro Cruzeiro',
    'Pouso Alegre',
    'Minas Gerais',
    '37550-000',
    'Matthew Paul Sherrouse',
    '',
    'ibbesperanca@hotmail.com',
    '(35) 3422-4534 , (35) 99119-7296',
    '',
    '000031',
    ''
) , 
(
	'Igreja Batista Bíblica',
    'Rua Coronel Leal, N° 25, bairro Nova Olinda',
    'Castanhal',
    'Pará',
    '68742-450',
    'Inácio Neves Cereja',
    'Só admite Bíblia do TR, e é independente.',
    '',
    '(091) 8181 6746',
    '',
    '000032',
    ''
) ,
(
	'Congregação Batista da Graça',
    'Rua Porto Colombo, N° 23, Bairro Vila Permanente',
    'Tucurui',
    'Pará',
    '68464-970',
    'Glailson Braga Pompeu',
    'Sendo ligada à Primeira Igreja Batista do Jardim das Oliveiras, de Fortaleza (vide acima), recebe visitas períodicas do Pastor David A. Zuhars Jr.',
    '',
    '(94) 778-3031 , (94) 9146-2114',
    '',
    '000033',
    ''
) ,
(
	'Primeira Igreja Batista Bíblica em Paraíba',
    'Rua Manoel Porto, 484, Bairro de Santa Rosa',
    'Campina Grande',
    'Paraíba',
    '58107-335',
    'Miguel Sebastião de Carvalho',
    'é independente, não associada',
    '',
    '(083) 332-0433',
    '',
    '000034',
    ''
) ,
(
	'Igreja Batista Bíblica das Malvinas',
    'Rua Olindina Pedro Santos Nº 27, Bairro das Malvinas',
    'Campina Grande',
    'Paraíba',
    '',
    'Luis Silva',
    'é independente, não associada',
    'prlussilva@yahoo.com.br , prluissilva@hotmail.com',
    '(083) 3339-5072',
    '',
    '000035',
    ''
) ,
(
	'Igreja Batista Bíblica Fundamentalista',
    'rua Antônio Bezerra s/n (em frente à Praça da Televisão)',
    'Esperança',
    'Paraíba',
    '58135-000',
    'Walter Gomes',
    'é independente, não associada',
    '',
    '(083) 9830-0475',
    '',
    '000036',
    ''
) ,
(
	'Congregação Batista Bíblica',
    'Rua Oscar Natanael de Moura, 109, Bairro Centro',
    'Juazeirinho',
    'Paraíba',
    '58660-000',
    '',
    '',
    '',
    '',
    '',
    '000037',
    ''
) ,
(
	'Igreja Batista Bíblica',
    'Rua José Marques Cavalcanti, 55, Conjunto da CEHAP',
    'Soledade',
    'Paraíba',
    '58155-000',
    'Faustino Anízio Gomes Costa',
    'é independente, não associada',
    'pr.anizio@bol.com.br',
    '(083) 3383-1643',
    '',
    '000038',
    'http://ibb-soledade.zip.net/'
) ,
(
	'Primeira Igreja Batista em Ribeirão Claro',
    'Rua Dr. João Pessoa, 09',
    'Ribeirão Claro',
    'Paraná',
    '',
    'Marcos Golinelli',
    '',
    'marcosgolinelli@informaxtelecom.com.br',
    '(43) 3536-1776',
    '',
    '000039',
    ''
) ,
(
	'Templo Batista Maranata',
    'Rua Isabel Oliveira Lima, 133, Jardim Monte Belo',
    'Londrina',
    'Paraná',
    '86041-500',
    'Manoel',
    '',
    'magtbm@hotmail.com',
    '(43) 3343-4007',
    '',
    '000040',
    'www.tbm.org.br '
) ,



// Second Half




(
		'Igreja Batista Missionária Bom Pastor',
        'Rua Humberto Macedo, 157 – Bairro: Rosa de Jesus',
        'Nova Iguaçu',
        'Rio de Janeiro',
        '26260-580',
        'Ismael Ribeiro',
        'Perto da Universidade UNIG, na Estrada de Madureira. Cultos: Terças às 19hs e Domingos às 10hrs. e 19hrs',
        '',
        '(21) 979289844',
        '',
        '000041',
        ''
	) , 
    (
		'Igreja Batista Regular Vida & Paz',
        'Rua José de Castro Pache de Farias, 634',
        'Niterói',
        'Rio de Janeiro',
        '24322-280',
        'Robert G. Kilko',
        '',
        'ServinginRio@aol.com',
        '(21) 2617-9037',
        '',
        '000042', 
        ''
	) ,
    (
		'Igreja Batista Fundamentalista de Monte Alegre',
        'Rua Alfredo Xavier, s/n',
        'Monte Alegre',
        'Rio Grande do Norte',
        '59182-000',
        'Marcus Vinicius',
        '',
        '',
        '',
        '',
        '000043',
        ''
	) ,
    (
		'Igreja Batista Regular da Cidade Satélite',
        'Rua das Perdizes, s/n – Bairro Cidade Satélite, Caixa Postal 1223',
        'Natal',
        'Rio Grande do Norte',
        '59067-480',
        'Henrique',
        '',
        '',
        '218-3030',
        '',
        '000044',
        ''
	) ,
    (
		'Igreja Batista Regular de Igapó',
        'Rua Isabel de Brito Lima, 415, Bairro de Igapó',
        'Natal',
        'Rio Grande do Norte',
        '59104-220',
        'Erinaldo',
        '',
        '',
        '214-7191',
        '',
        '000045',
        ''
	) ,
    (
		'Igreja Evangélica Batista de Candelária',
        'Rua Valdir Targino, 3585 – Bairro Candelária',
        'Natal',
        'Rio Grande do Norte',
        '59065-670',
        'Jean Carlos',
        '',
        '',
        '206-8315',
        '',
        '000046',
        ''
	) ,
    (
		'Igreja Batista Regular Independente',
        '',
        'Parnamirim',
        'Rio Grande do Norte',
        '',
        'Carlos',
        '',
        '',
        '',
        '',
        '000047',
        ''
	) ,
    (
		'Igreja Batista Fundamentalista de Santa Cruz',
        'Rua Marechal Castelo Branco, 320 - Bairro 3 a 1',
        'Santa Cruz',
        'Rio Grande do Norte',
        '59200-000',
        'Soares',
        '',
        '',
        '',
        '',
        '000048',
        ''
	) ,
    (
		'Igreja Batista Bíblica Memorial',
        'Av: José Lopes de Oliveira, caixa postal 31, Centro',
        'Machadinho do Oeste',
        'Rondônia',
        '78948-000',
        'Ailton Amaral Ribeiro',
        '',
        'ailltonamaral@gmail.com.',
        '69-3581-3766 , 92486232',
        '',
        '000049',
        ''
	) ,
    (
		'Primeira Igreja Batista Independente de Ouro Preto do Oeste',
        '',
        'Ouro Preto do Oeste',
        'Rondônia',
        '',
        '',
        '(Nome Provisório), Endereço: Entre em contato com o pastor',
        'Joao@ConhecendoDeus.com.br',
        '',
        '',
        '000050',
        ''
	) ,
    (
		'Igreja Batista Regular da Graça',
        'Rua Waldemar Coelho de Aguiar, 1137, Bairro União',
        'Boa Vista',
        'Roraima',
        '69313-778',
        'Aureliano Colaço da Costa Neto',
        '',
        '',
        '(95) 3628-5135',
        '',
        '000051',
        ''
	) ,
    (
		'Igreja Batista Bíblica de Florianópolis',
        'Rua Irmã Bonavita 1047, bairro Coloninha (Capoeiras)',
        'Florianópolis',
        'Santa Catarina',
        '88090-150',
        'Moisés Damázio',
        '',
        'the.damazios@gmail.com',
        '(48) 3348-6359 , 99984 3375 , 48 3240 6033 (casa) , 48 99927 7977',
        '',
        '000052',
        ''
	) ,
    (
		'Igreja Batista Vitória',
        'Rua Oceano Pacífico, 400, Bairro Boehmerwald',
        'Joinville',
        'Santa Catarina',
        '89235-413',
        'James Timothy Allen',
        'Co-Pastor: Ricardo Henrique Hogrefe',
        'jamesallen@mwbm.org , ricardoemonicahogrefe@yahoo.com.br',
        '(47) 9624-1883 , 47-9934-4858',
        '',
        '000053',
        'www.thejoinvilleproject.com'
	) ,
    (
		'Igreja Batista Bíblica',
        'Caixa Postal 95, Rua Arapongas s/n, Centro',
        'Penha',
        'Santa Catarina',
        '88385-000',
        'Carlos Alberto Vasconcelos',
        'Obreiro: Joel Rodrigues - Fone: (47) 3674044',
        '',
        '(47) 347-0210 , (47) 345-1020',
        '',
        '000054',
        ''
	) ,
    (
		'Igreja Batista Bíblica',
        'Rua C-27, 397',
        'Barretos',
        'São Paulo',
        '14781-471',
        'João Francisco Teodoro Filho',
        '',
        'batistabiblica@ig.com.br',
        '(17) 3324-2518',
        '',
        '000055',
        ''
	) ,
    (
		'Igreja Batista Memorial de Bauru',
        'Rua 12 de Outubro, nº 4-3 (antes era Rui Barbosa, 6-14), Jardim Bela Vista',
        'Bauru',
        'São Paulo',
        '17060-300',
        'Antonio Carlos Dias',
        '*Outro endereço?* Rua Padre Nóbrega, 11.22, Jardim Bela Vista, 17060-450 Bauru, São Paulo.  Diácono Morel: 3232 7404',
        '',
        '(14) 3232-5025',
        '',
        '000056',
        ''
	) ,
    (
		'Primeira Igreja Batista Independente em Catanduva',
        'Rua Francisco Beltrão, 138',
        'Catanduva',
        'São Paulo',
        '15801-447',
        '',
        'Sem pastor em 2008',
        'ibicatanduva@terra.com.br',
        '(17) 3523-2675',
        '',
        '000057',
        ''
	) ,
    (
		'Igreja Batista Fundamentalista Bíblica',
        'Rua Minas Gerais 130, bairro Jaciporã',
        'Dracena',
        'São Paulo',
        '',
        'Roberto Gomes',
        'Correspondência: Rua Prof. Vânia Maria do Vale Pereira, 294, bairro Jaciporã, CEP 17900-000',
        '',
        '(18) 9708-6246',
        '',
        '000058',
        ''
	) ,
    (
		'Igreja Batista Emanuel',
        'Rua Dr. Amadeu Sacchi, 131',
        'Jundiaí',
        'São Paulo',
        '13214-280',
        'Lawrence Willian Barrett',
        '',
        '',
        '',
        '',
        '000059',
        'www.ministeriosibe.com.br , www.bibliaaberta.com.br'
	) ,
    (
		'Congregação Batista Independente',
        'Rua Xavantes, 77, Vila Tupi, Várzea Paulistas',
        'Jundiaí',
        'São Paulo',
        '13225-020',
        'Inácio Barbosa',
        '',
        '',
        '',
        '',
        '000060',
        'www.batistasoriginais.org'
	) ,
    (
		'Igreja Batista da Fé',
        'Rua Ana Cândida de Souza Gemender, 90, Jardim Nacional',
        'Marília',
        'São Paulo',
        '',
        'Gilberto Stefano',
        '*Outro endereço?* Rua Jamil Dib Lufti, 165, Jardim Santa Clara, CEP 17523-341.',
        '',
        '(14) 3451-1434',
        '',
        '000061',
        ''
	) ,
    (
		'Igreja Batista em Jardim das Flores',
        'Rua Flor de Amoras, 85, Jardim das Flores',
        'Osasco',
        'São Paulo',
        '06114-060',
        'Eduardo Alves Cadete',
        '',
        'igrejabatistaosasco@uol.com.br',
        '(11) 3681-1178',
        '',
        '000062',
        'http://www.igrejabatistaosasco.com.br/'
	) ,
    (
		'Igreja Batista Regular em Jardim Santo Antônio',
        'Avenida Santiago Rodilha, 515, Bairro Jardim Santo Antônio',
        'Osasco',
        'São Paulo',
        '06154-000',
        'Jorge Antônio Gameiro',
        '',
        'jagameiro@ig.com.br',
        '',
        '',
        '000063',
        ''
	) , 
    (
		'Igreja Batista da Boa Esperança',
        'Rua Fernando Prestes, 367, Vila Boa Esperança',
        'Ourinhos',
        'São Paulo',
        '19912-130',
        'Israel Teixeira Barbosa',
        ' Residência: Rua Luiz de Carvalho, 128, Jd Anchieta, 19915-620, Ourinhos, SP.',
        '',
        '(14) 3324-6328',
        '',
        '000064',
        ''
	) , 
    (
		'Igreja Batista Livre',
        'Av. Jonas Alves de Mello, 2.442',
        'Pereira Barreto',
        'São Paulo',
        '15370-000',
        'Márcio Morel de Souza',
        'Correspondência: Rua Benigno Lopes, 1610, 15370-000.',
        'mmorel@clubinter.com.br',
        '',
        '',
        '000065',
        ''
	) , 
    (
		'Igreja Batista Bereana',
        'Rua Glória de Souza, 415, Mário Amato',
        'Presidente Prudente',
        'São Paulo',
        '19064-135',
        'João Carlos Fachini;',
        'Trabalho iniciado pelo saudoso Pr. Calvin Gardner, sob autoridade da igreja Wooster Baptist Temple.',
        '',
        '(18) 3903-3944',
        '',
        '000066',
        'http://ibbprudente.com.br/'
	) , 
    (
		'Igreja Batista Bíblica em Valparaíso',
        'Rua Tupi, 461 - Vila Valparaíso',
        'Santo André',
        'São Paulo',
        '',
        'Paulo Guedes Soares',
        '',
        'prpauloguedes@terra.com.br',
        '(11) 4426-9624',
        '',
        '000067',
        ''
	) , 
    (
		'Primeira Igreja Batista Bíblica em Cidade Ademar',
        'Av. Celso dos Santos, 959, Jardim das Oliveiras',
        'São Paulo',
        'São Paulo',
        '04658-241',
        'Ebenezer Rodrigues',
        'pastores Josué Pereira Félix e Ebenezer Rodrigues (pr.ebenezer at pibbca.org.br).',
        'pr.ebenezer@pibbca.org.br',
        ' 5563-6391 , 6527; 5562-2834',
        '',
        '000068',
        'http://www.pibbca.org.br/'
	) , 
    (
		'Templo Batista de Indianópolis',
        'Alameda dos Jurupis, 1270 - Indianópolis',
        'São Paulo',
        'São Paulo',
        '04088-004',
        'Marcos Antônio da Silva',
        'Pastores: Marcos Antônio da Silva (marcosigreja@uol.com.br ), Alexandre Dutra (pr.alexandredutra@ig.com.br ) e Thomas L. Gilmer (thomaslgilmer@gmail.com )',
        'templobatistadeindianopolis@gmail.com',
        '(11) 5543-4122',
        '',
        '000069',
        'http://templobatista.org/'
	) , 
    (
		'Igreja Batista da Bíblia',
        'Alameda dos Jurupis, 1270 - Fundos, Indianópolis',
        'São Paulo',
        'São Paulo',
        '04088-004',
        'Dan Bennett',
        '',
        'faleconosco@ibb.adm.br',
        '(11) 4044-5002',
        '',
        '000070',
        'http://www.ibb.adm.br'
	) , 
    (
		'Igreja Batista Betel Independente',
        'Rua das Flautas Transversais, 115 - Bairro: Estância Tangará',
        'São Paulo',
        'São Paulo',
        '04933-010',
        'Waldir Ferro',
        '',
        'contato@ibbindependente.com , pwferro@hotmail.com',
        '',
        '',
        '000071',
        'http://ibbindependente.com/'
	) , 
    (
		'Igreja Batista Independente em Casa Verde',
        'Rua Maria Medeiros, 50 - Casa Verde',
        'São Paulo',
        'São Paulo',
        '02532-000',
        'Fábio Moreira',
        'Dirigente: Irmãos Fábio Moreira e Moacir Menha. Terças às 20hs (culto oração) e Domingos às 9hs e 18h30.',
        '',
        '',
        '',
        '000072',
        ''
	) , 
    (
		'Igreja Batista em Parque Ipê',
        'Rua Inácio Cervantes, 607 – Pq. Ipê (zona oeste)',
        'São Paulo',
        'São Paulo',
        '05572-000',
        'Timóteo Pina',
        '',
        'timoteopina@hotmail.com',
        '(11) 4148-4841',
        '',
        '000073',
        ''
	) , 
    (
		'Missão São Paulo (Batista)',
        'Rua Comandante Taylor, 73 (Bairro: Ipiranga (Terminal-Metrô Sacomã))',
        'São Paulo',
        'São Paulo',
        '04218-000',
        'Abner Araújo',
        '(congregação do Tabernáculo Metropolitano de Londres, Inglaterra - igreja batista de Charles Spurgeon, atualmente dirigida por Peter Masters)',
        'contato@missaosaopaulo.org',
        '(11) 96076.2001',
        '',
        '000074',
        'http://www.missaosaopaulo.org/'
	) , 
    (
		'Igreja Batista Conservadora e Fundamentalista em Jardim das Rosas',
        'Av. Maria Amália Lopes de Azevedo, 3.676 – Jardim das Rosas ',
        'São Paulo',
        'São Paulo',
        '02-350002',
        'J. Sérgio Ackel',
        '',
        'igbjrosa@yahoo.com.br',
        '',
        '',
        '000075',
        ''
	) , 
    (
		'Igreja Batista Nova Vida',
        'Rua Francisco Soares, 416 (em frente ao campo da Portuguesa e 850m do Metrô Vila das Belezas (Linha 5 – Lilás) – Jardim Ingá',
        'São Paulo',
        'São Paulo',
        '05774-300',
        'Harold R. Gilmer',
        'Cultos: Quartas às 19:30; Domingos – Escola Bíblica às 9:30 – Culto às 19:00',
        '',
        '(11) 5816-9419',
        '',
        '000076',
        ''
	) , 
    (
		'Igreja Batista Livre em Sud Menucci',
        'Av. Pioneiros, 387 – Centro – Caixa Postal 9 ',
        'Sud Menucci',
        'São Paulo',
        '15360-970',
        'Ari Adorno de Abreu',
        '',
        '',
        '(18) 3786-1636',
        '',
        '000077',
        ''
	) , 
    (
		'Congregação Batista Bíblica Jardim São Luís',
        'R: Francisco Xavier de Sales, 811 - Jd. Guarujá',
        'São Paulo',
        'São Paulo',
        '05830-250',
        'Sérgio Barbosa',
        '',
        'ibbjsl@uol.com.br , sergiobsp@hotmail.com.br',
        '(011) 5563-2613 , (011) 9553-6772',
        '',
        '000078',
        'http://batistaemsaoluis.blogspot.com'
	) , 
    (
		'Congregação Batista Bíblica em Jardim Lucélia',
        'R. Charles Laveran, 280 - Jd. Lucélia',
        'São Paulo',
        'São Paulo',
        '04852-480',
        'Marcos Cruz Felipe',
        '',
        '(011) 5528-1120 , (11) 6200-0721',
        'ibbjl@ig.com.br',
        '',
        '000079',
        ''
	) , 
    (
		'Igreja Batista Emanuel de Limeira',
        'Av. Luís Vaz de Camões, 330 - Jd. Caieiras',
        'Limeira',
        'São Paulo',
        '13483-170',
        'Garry Lee Tyler',
        '',
        '',
        '(19) 3701.4937 , (19) 98822.5457',
        '',
        '000080',
        ''
	) , 
    (
		'Igreja Batista Âncora',
        'Rua Maria Bellini Fachini, 56 - Jd. Fátima',
        'Araras',
        'São Paulo',
        '13-607095',
        'Deogenilson Evangelista Santana',
        '',
        'delsantana@ig.com.br',
        '(19) 4124-0343 , (19) 98313-0492',
        '',
        '000081',
        ''
	) , 
    (
		'Igreja Batista Fundamental',
        'Rua Emílio Bertozzi c/ Travessa Nazaré, 197/15 - Algodoal',
        'Piracicaba',
        'São Paulo',
        '13405-420',
        'Coy Wilson Shaw Jr.',
        '',
        '',
        '(19) 3421.0912 , (19) 98213.1956',
        '',
        '000082',
        ''
	) , 
    (
		'Primeira Igreja Batista de Parque Bristol',
        'Avenida José Caetano da Rocha, 379',
        'São Paulo',
        'São Paulo',
        '04193-300',
        'Rinaldo Belisário Jr',
        '',
        '',
        '(11) 3853-2619',
        '',
        '000083',
        ''
	)
